### ISSUE TITLE
ConBee after pairing no configuration available

### ISSUE THREAD

**Issue by arteck** [Koenkk/zigbee-herdsman#171]
the message is` "Failed to configure 0x00000000`
after pairing the conBee not send the configuring message to the Device as sample osram plug or hue RWL021

```
2020-05-03 09:54:04.677	error	at rejected (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65))
2020-05-03 09:54:04.677	error	at Generator.throw (<anonymous>)
2020-05-03 09:54:04.677	error	at Endpoint.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:244:23)
2020-05-03 09:54:04.677	error	(1328) Failed to configure 0x001788010807ecb2 RWL021, attempt 1 (Error: Bind 0x001788010807ecb2/1 genOnOff from '0x00212effff048af7/1' failed
```

**Comment by arteck** [comment]
new version but not better

**Comment by ChrisHae** [comment]
How it is now with the latest version of the dev branch?

**Comment by MattWestb** [comment]
Bump
