### ISSUE TITLE
Failure to add Konke Device.

### ISSUE THREAD

**Issue by tb-killa** [Koenkk/zigbee-herdsman#25]
Hi @Koenkk 

I see this if i want to add the Konke Motion Device because it doesnt seem to add correctly.

```

  zigbee-herdsman:unpi:parser <-- [254,23,68,129,0,0,32,0,12,100,1,1,0,2,0,190,246,101,0,0,3,25,16,0,12,100,29,202] +24s
  zigbee-herdsman:unpi:parser --- parseNext [254,23,68,129,0,0,32,0,12,100,1,1,0,2,0,190,246,101,0,0,3,25,16,0,12,100,29,202] +0ms
  zigbee-herdsman:unpi:parser --> parsed 23 - 2 - 4 - 129 - [
d��e
d] - 202 +1ms
  zigbee-herdsman:znp:AREQ <-- AF - incomingMsg - {"groupid":0,"clusterid":32,"srcaddr":25612,"srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"linkquality":2,"securityuse":0,"timestamp":6682302,"transseqnumber":0,"len":3,"data":{"type":"Buffer","data":[25,16,0]}} +24s
  zigbee-herdsman:controller:log Received ZCL data '{"frame":{"Header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":true},"transactionSequenceNumber":16,"manufacturerCode":null,"commandIdentifier":0},"Payload":{},"ClusterID":32},"networkAddress":25612,"endpoint":1,"linkquality":2,"groupID":0}' +24s
  zigbee-herdsman:unpi:parser --- parseNext [] +5ms
  zigbee-herdsman:controller:log Skipping command 'checkin' because it is missing from the lookup +2ms
  zigbee-herdsman:unpi:parser <-- [254,28,68,129,0,0,1,2,12,100,1,1,0,0,0,58,64,102,0,0,8,24,17,10,0,0,41,138,7,12,100,29,116] +6s
  zigbee-herdsman:unpi:parser --- parseNext [254,28,68,129,0,0,1,2,12,100,1,1,0,0,0,58,64,102,0,0,8,24,17,10,0,0,41,138,7,12,100,29,116] +1ms
  zigbee-herdsman:unpi:parser --> parsed 28 - 2 - 4 - 129 - [
d:@f
  zigbee-herdsman:unpi:parser )�
d] - 116 +1ms
```

It seems to be that some Encoding Problem occures ?

**Comment by Koenkk** [comment]
I dont see anything wrong here, the strange characters you see are because the bytes are decoded as utf8.

**Comment by tb-killa** [comment]
Hi @Koenkk 

The Device doesnt seems to allow fully interview:

```
serialport/binding-abstract read +290ms
  serialport/bindings/unixRead Starting read +289ms
  serialport/bindings/unixRead Finished read 17 bytes +1ms
  serialport/stream binding.read finished +293ms
  zigbee-herdsman:unpi:parser <-- [254,12,69,202,176,138,231,123,233,254,255,215,107,8,0,0,121] +295ms
  zigbee-herdsman:unpi:parser --- parseNext [254,12,69,202,176,138,231,123,233,254,255,215,107,8,0,0,121] +1ms
  zigbee-herdsman:unpi:parser --> parsed 12 - 2 - 5 - 202 - [���{����] - 121 +1ms
  zigbee-herdsman:znp:AREQ <-- ZDO - tcDeviceInd - {"nwkaddr":35504,"extaddr":"0x086bd7fffee97be7","parentaddr":0} +343ms
  zigbee-herdsman:unpi:parser --- parseNext [] +3ms
  zigbee-herdsman:controller:log Device joined '0x086bd7fffee97be7' +344ms
  zigbee-herdsman:controller:log Interview '0x086bd7fffee97be7' start +1ms
  zigbee-herdsman:controller:device Interview - start device '0x086bd7fffee97be7' +2m
  zigbee2mqtt:info 9/18/2019, 11:17:21 AM Starting interview of 'konke_motionsensor'
  zigbee2mqtt:info 9/18/2019, 11:17:21 AM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendlyName":"konke_motionsensor"}}'
  serialport/stream _read reading +16ms
  serialport/binding-abstract read +19ms
  serialport/bindings/unixRead Starting read +19ms
  serialport/bindings/unixRead waiting for readable because of code: EAGAIN +2ms
  serialport/bindings/poller Polling for "readable" +24ms
  serialport/bindings/poller received "readable" +1ms
  serialport/binding-abstract read +6ms
  serialport/bindings/unixRead Starting read +2ms
  serialport/bindings/unixRead Finished read 8 bytes +1ms
  serialport/stream binding.read finished +8ms
  zigbee-herdsman:unpi:parser <-- [254,3,68,128,0,1,4,194] +19ms
  zigbee-herdsman:unpi:parser --- parseNext [254,3,68,128,0,1,4,194] +0ms
  zigbee-herdsman:unpi:parser --> parsed 3 - 2 - 4 - 128 - [] - 194 +1ms
  zigbee-herdsman:znp:AREQ <-- AF - dataConfirm - {"status":0,"endpoint":1,"transid":4} +22ms
  zigbee-herdsman:unpi:parser --- parseNext [] +1ms
  zigbee-herdsman:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":35504,"nwkaddrofinterest":35504} +359ms
  zigbee-herdsman:unpi:writer --> frame [254,4,37,2,176,138,176,138,35] +359ms
  serialport/stream _write 9 bytes of data +7ms
  serialport/binding-abstract write 9 bytes +9ms
  serialport/bindings/unixWrite Starting write 9 bytes offset 0 bytesToWrite 9 +345ms
  serialport/stream _read reading +4ms
  serialport/binding-abstract read +3ms
  serialport/bindings/unixRead Starting read +12ms
  serialport/bindings/unixWrite write returned null 9 +5ms
  serialport/bindings/unixWrite wrote 9 bytes +1ms
  serialport/bindings/unixWrite Finished writing 9 bytes +0ms
  serialport/stream binding.write write finished +4ms
  serialport/bindings/unixRead waiting for readable because of code: EAGAIN +4ms
  serialport/bindings/poller Polling for "readable" +19ms
  serialport/bindings/poller received "readable" +1ms
  serialport/binding-abstract read +7ms
  serialport/bindings/unixRead Starting read +3ms
  serialport/bindings/unixRead Finished read 6 bytes +1ms
  serialport/stream binding.read finished +6ms
  zigbee-herdsman:unpi:parser <-- [254,1,101,2,0,102] +19ms
  zigbee-herdsman:unpi:parser --- parseNext [254,1,101,2,0,102] +1ms
  zigbee-herdsman:unpi:parser --> parsed 1 - 3 - 5 - 2 - [] - 102 +1ms
  zigbee-herdsman:znp:SRSP <-- ZDO - nodeDescReq - {"status":0} +344ms
  zigbee-herdsman:unpi:parser --- parseNext [] +3ms
  serialport/stream _read reading +8ms
  serialport/binding-abstract read +11ms
  serialport/bindings/unixRead Starting read +10ms
  serialport/bindings/unixRead waiting for readable because of code: EAGAIN +1ms
  serialport/bindings/poller Polling for "readable" +14ms
  serialport/bindings/poller received "readable" +586ms
  serialport/binding-abstract read +589ms
  serialport/bindings/unixRead Starting read +588ms
  serialport/bindings/unixRead Finished read 23 bytes +1ms
  serialport/stream binding.read finished +591ms
  zigbee-herdsman:unpi:parser <-- [254,18,69,130,176,138,0,176,138,2,64,128,2,16,82,82,0,0,44,82,0,0,123] +594ms
  zigbee-herdsman:unpi:parser --- parseNext [254,18,69,130,176,138,0,176,138,2,64,128,2,16,82,82,0,0,44,82,0,0,123] +1ms
  zigbee-herdsman:unpi:parser --> parsed 18 - 2 - 5 - 130 - [����@�RR,R] - 123 +1ms
  zigbee-herdsman:znp:AREQ <-- ZDO - nodeDescRsp - {"srcaddr":35504,"status":0,"nwkaddr":35504,"logicaltype_cmplxdescavai_userdescavai":2,"apsflags_freqband":64,"maccapflags":128,"manufacturercode":4098,"maxbuffersize":82,"maxintransfersize":82,"servermask":11264,"maxouttransfersize":82,"descriptorcap":0} +622ms
  zigbee-herdsman:unpi:parser --- parseNext [] +2ms
  serialport/stream _read reading +8ms
  serialport/binding-abstract read +10ms
  serialport/bindings/unixRead Starting read +9ms
  serialport/bindings/unixRead waiting for readable because of code: EAGAIN +1ms
  serialport/bindings/poller Polling for "readable" +12ms
  zigbee-herdsman:controller:device Interview - got node descriptor for device '0x086bd7fffee97be7' +651ms
  zigbee-herdsman:znp:SREQ --> ZDO - activeEpReq - {"dstaddr":35504,"nwkaddrofinterest":35504} +632ms
  zigbee-herdsman:unpi:writer --> frame [254,4,37,5,176,138,176,138,36] +632ms
  serialport/stream _write 9 bytes of data +11ms
  serialport/binding-abstract write 9 bytes +11ms
  serialport/bindings/unixWrite Starting write 9 bytes offset 0 bytesToWrite 9 +626ms
  serialport/bindings/unixWrite write returned null 9 +2ms
  serialport/bindings/unixWrite wrote 9 bytes +0ms
  serialport/bindings/unixWrite Finished writing 9 bytes +0ms
  serialport/stream binding.write write finished +4ms
  serialport/bindings/poller received "readable" +19ms
  serialport/binding-abstract read +11ms
  serialport/bindings/unixRead Starting read +21ms
  serialport/bindings/unixRead Finished read 6 bytes +1ms
  serialport/stream binding.read finished +10ms
  zigbee-herdsman:unpi:parser <-- [254,1,101,5,0,97] +29ms
  zigbee-herdsman:unpi:parser --- parseNext [254,1,101,5,0,97] +1ms
  zigbee-herdsman:unpi:parser --> parsed 1 - 3 - 5 - 5 - [] - 97 +1ms
  zigbee-herdsman:znp:SRSP <-- ZDO - activeEpReq - {"status":0} +632ms
  zigbee-herdsman:unpi:parser --- parseNext [] +2ms
  serialport/stream _read reading +7ms
  serialport/binding-abstract read +11ms
  serialport/bindings/unixRead Starting read +10ms
  serialport/bindings/unixRead waiting for readable because of code: EAGAIN +1ms
  serialport/bindings/poller Polling for "readable" +15ms
  serialport/bindings/poller received "readable" +245ms
  serialport/binding-abstract read +249ms
  serialport/bindings/unixRead Starting read +247ms
  serialport/bindings/unixRead Finished read 12 bytes +1ms
  serialport/stream binding.read finished +251ms
  zigbee-herdsman:unpi:parser <-- [254,7,69,133,176,138,0,176,138,1,1,199] +254ms
  zigbee-herdsman:unpi:parser --- parseNext [254,7,69,133,176,138,0,176,138,1,1,199] +0ms
  zigbee-herdsman:unpi:parser --> parsed 7 - 2 - 5 - 133 - [����] - 199 +1ms
  zigbee-herdsman:znp:AREQ <-- ZDO - activeEpRsp - {"srcaddr":35504,"status":0,"nwkaddr":35504,"activeepcount":1,"activeeplist":[1]} +289ms
  zigbee-herdsman:unpi:parser --- parseNext [] +1ms
  serialport/stream _read reading +6ms
  serialport/binding-abstract read +7ms
  serialport/bindings/unixRead Starting read +7ms
  serialport/bindings/unixRead waiting for readable because of code: EAGAIN +3ms
  serialport/bindings/poller Polling for "readable" +13ms
  zigbee-herdsman:controller:device Interview - got active endpoints for device '0x086bd7fffee97be7' +293ms
  zigbee-herdsman:znp:SREQ --> ZDO - simpleDescReq - {"dstaddr":35504,"nwkaddrofinterest":35504,"endpoint":1} +294ms
  zigbee-herdsman:unpi:writer --> frame [254,5,37,4,176,138,176,138,1,37] +295ms
  serialport/stream _write 10 bytes of data +17ms
  serialport/binding-abstract write 10 bytes +18ms
  serialport/bindings/unixWrite Starting write 10 bytes offset 0 bytesToWrite 10 +294ms
  serialport/bindings/unixWrite write returned null 10 +2ms
  serialport/bindings/unixWrite wrote 10 bytes +1ms
  serialport/bindings/unixWrite Finished writing 10 bytes +1ms
  serialport/stream binding.write write finished +7ms
  serialport/bindings/poller received "readable" +23ms
  serialport/binding-abstract read +11ms
  serialport/bindings/unixRead Starting read +27ms
  serialport/bindings/unixRead Finished read 6 bytes +1ms
  serialport/stream binding.read finished +9ms
  zigbee-herdsman:unpi:parser <-- [254,1,101,4,0,96] +38ms
  zigbee-herdsman:unpi:parser --- parseNext [254,1,101,4,0,96] +1ms
  zigbee-herdsman:unpi:parser --> parsed 1 - 3 - 5 - 4 - [] - 96 +1ms
  zigbee-herdsman:znp:SRSP <-- ZDO - simpleDescReq - {"status":0} +299ms
  zigbee-herdsman:unpi:parser --- parseNext [] +3ms
  serialport/stream _read reading +10ms
  serialport/binding-abstract read +15ms
  serialport/bindings/unixRead Starting read +13ms
  serialport/bindings/unixRead waiting for readable because of code: EAGAIN +2ms
  serialport/bindings/poller Polling for "readable" +20ms
  serialport/bindings/poller received "readable" +652ms
  serialport/binding-abstract read +656ms
  serialport/bindings/unixRead Starting read +654ms
  serialport/bindings/unixRead Finished read 29 bytes +1ms
  serialport/stream binding.read finished +660ms
  zigbee-herdsman:unpi:parser <-- [254,24,69,132,176,138,0,176,138,18,1,4,1,2,4,0,4,0,0,1,0,3,0,0,5,1,3,0,200] +664ms
  zigbee-herdsman:unpi:parser --- parseNext [254,24,69,132,176,138,0,176,138,18,1,4,1,2,4,0,4,0,0,1,0,3,0,0,5,1,3,0,200] +1ms
  zigbee-herdsman:unpi:parser --> parsed 24 - 2 - 5 - 132 - [����] - 200 +1ms
  zigbee-herdsman:znp:AREQ <-- ZDO - simpleDescRsp - {"srcaddr":35504,"status":0,"nwkaddr":35504,"len":18,"endpoint":1,"profileid":260,"deviceid":1026,"deviceversion":0,"numinclusters":4,"inclusterlist":[0,1,3,1280],"numoutclusters":1,"outclusterlist":[3]} +712ms
  zigbee-herdsman:unpi:parser --- parseNext [] +4ms
  zigbee-herdsman:controller:device Interview - got simple descriptor for endpoint '1' device '0x086bd7fffee97be7' +701ms
  serialport/stream _read reading +11ms
  serialport/binding-abstract read +14ms
  serialport/bindings/unixRead Starting read +13ms
  serialport/bindings/unixRead waiting for readable because of code: EAGAIN +2ms
  serialport/bindings/poller Polling for "readable" +17ms
  zigbee-herdsman:znp:SREQ --> AF - dataRequest - {"dstaddr":35504,"destendpoint":1,"srcendpoint":1,"clusterid":0,"transid":5,"options":0,"radius":30,"len":9,"data":{"type":"Buffer","data":[16,3,0,4,0,5,0,7,0]}} +711ms
  zigbee-herdsman:unpi:writer --> frame [254,19,36,1,176,138,1,1,0,0,5,0,30,9,16,3,0,4,0,5,0,7,0,11] +711ms
  serialport/stream _write 24 bytes of data +14ms
  serialport/binding-abstract write 24 bytes +14ms
  serialport/bindings/unixWrite Starting write 24 bytes offset 0 bytesToWrite 24 +706ms
  serialport/bindings/unixWrite write returned null 24 +2ms
  serialport/bindings/unixWrite wrote 24 bytes +0ms
  serialport/bindings/unixWrite Finished writing 24 bytes +1ms
  serialport/stream binding.write write finished +5ms
  serialport/bindings/poller received "readable" +20ms
  serialport/binding-abstract read +10ms
  serialport/bindings/unixRead Starting read +22ms
  serialport/bindings/unixRead Finished read 6 bytes +1ms
  serialport/stream binding.read finished +8ms
  zigbee-herdsman:unpi:parser <-- [254,1,100,1,0,100] +32ms
  zigbee-herdsman:unpi:parser --- parseNext [254,1,100,1,0,100] +1ms
  zigbee-herdsman:unpi:parser --> parsed 1 - 3 - 4 - 1 - [] - 100 +1ms
  zigbee-herdsman:znp:SRSP <-- AF - dataRequest - {"status":0} +706ms
PuTTY  zigbee-herdsman:unpi:parser --- parseNext [] +3ms
  serialport/stream _read reading +8ms
  serialport/binding-abstract read +12ms
  serialport/bindings/unixRead Starting read +11ms
  serialport/bindings/unixRead waiting for readable because of code: EAGAIN +1ms
  serialport/bindings/poller Polling for "readable" +16ms
  serialport/bindings/poller received "readable" +2s
  serialport/binding-abstract read +2s
  serialport/bindings/unixRead Starting read +2s
  serialport/bindings/unixRead Finished read 8 bytes +1ms
  serialport/stream binding.read finished +2s
  zigbee-herdsman:unpi:parser <-- [254,3,68,128,0,1,5,195] +2s
  zigbee-herdsman:unpi:parser --- parseNext [254,3,68,128,0,1,5,195] +1ms
  zigbee-herdsman:unpi:parser --> parsed 3 - 2 - 4 - 128 - [] - 195 +1ms
  zigbee-herdsman:znp:AREQ <-- AF - dataConfirm - {"status":0,"endpoint":1,"transid":5} +2s
  zigbee-herdsman:unpi:parser --- parseNext [] +2ms
  serialport/stream _read reading +7ms
  serialport/binding-abstract read +10ms
  serialport/bindings/unixRead Starting read +10ms
  serialport/bindings/unixRead waiting for readable because of code: EAGAIN +1ms
  serialport/bindings/poller Polling for "readable" +14ms
PuTTY  zigbee-herdsman:controller:error Interview failed for '0x086bd7fffee97be7 with error 'Error: Timeout - 35504 - 1 - 3 - 1 after 10000ms' +2m
  zigbee2mqtt:error 9/18/2019, 11:17:32 AM Failed to interview 'konke_motionsensor', device has not succesfully been paired
  zigbee2mqtt:info 9/18/2019, 11:17:32 AM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_failed","meta":{"friendlyName":"konke_motionsensor"}}'





  zigbee-herdsman:controller:log Permit joining +1m
  zigbee-herdsman:znp:SREQ --> ZDO - mgmtPermitJoinReq - {"addrmode":15,"dstaddr":65532,"duration":254,"tcsignificance":0} +1m
  zigbee-herdsman:unpi:writer --> frame [254,5,37,54,15,252,255,254,0,228] +1m
  serialport/stream _write 10 bytes of data +1m
  serialport/binding-abstract write 10 bytes +1m
  serialport/bindings/unixWrite Starting write 10 bytes offset 0 bytesToWrite 10 +1m
  serialport/bindings/unixWrite write returned null 10 +1ms
  serialport/bindings/unixWrite wrote 10 bytes +1ms
  serialport/bindings/unixWrite Finished writing 10 bytes +0ms
  serialport/stream binding.write write finished +4ms
  serialport/bindings/poller received "readable" +1m
  serialport/binding-abstract read +14ms
  serialport/bindings/unixRead Starting read +1m
  serialport/bindings/unixRead Finished read 70 bytes +1ms
  serialport/stream binding.read finished +12ms
  zigbee-herdsman:unpi:parser <-- [254,59,68,129,0,0,0,0,176,138,1,1,0,0,0,253,157,127,0,0,39,24,3,1,4,0,0,66,5,75,111,110,107,101,5,0,0,66,16,51,65,70,69,49,52,48,49,48,52,48,50,48,48,48,68,7,0,0,48,0,176,138,29,161,254,1,101,54,0,82] +1m
  zigbee-herdsman:unpi:parser --- parseNext [254,59,68,129,0,0,0,0,176,138,1,1,0,0,0,253,157,127,0,0,39,24,3,1,4,0,0,66,5,75,111,110,107,101,5,0,0,66,16,51,65,70,69,49,52,48,49,48,52,48,50,48,48,48,68,7,0,0,48,0,176,138,29,161,254,1,101,54,0,82] +1ms
  zigbee-herdsman:unpi:parser --> parsed 59 - 2 - 4 - 129 - [���'BKonkeB3AFE14010402000D0��] - 161 +1ms
  zigbee-herdsman:znp:AREQ <-- AF - incomingMsg - {"groupid":0,"clusterid":0,"srcaddr":35504,"srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"linkquality":0,"securityuse":0,"timestamp":8363517,"transseqnumber":0,"len":39,"data":{"type":"Buffer","data":[24,3,1,4,0,0,66,5,75,111,110,107,101,5,0,0,66,16,51,65,70,69,49,52,48,49,48,52,48,50,48,48,48,68,7,0,0,48,0]}} +1m
  zigbee-herdsman:controller:log Received ZCL data '{"frame":{"Header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":true},"transactionSequenceNumber":3,"manufacturerCode":null,"commandIdentifier":1},"Payload":[{"attrId":4,"status":0,"dataType":66,"attrData":"Konke"},{"attrId":5,"status":0,"dataType":66,"attrData":"3AFE14010402000D"},{"attrId":7,"status":0,"dataType":48,"attrData":0}],"ClusterID":0},"networkAddress":35504,"endpoint":1,"linkquality":0,"groupID":0}' +26ms
  zigbee-herdsman:unpi:parser --- parseNext [254,1,101,54,0,82] +4ms
  zigbee-herdsman:unpi:parser --> parsed 1 - 3 - 5 - 54 - [] - 82 +0ms
  zigbee-herdsman:znp:SRSP <-- ZDO - mgmtPermitJoinReq - {"status":0} +1m
  zigbee-herdsman:unpi:parser --- parseNext [] +2ms
  zigbee2mqtt:debug 9/18/2019, 11:18:31 AM Received Zigbee message from 'konke_motionsensor' of type 'readResponse' with data '{"manufacturerName":"Konke","modelId":"3AFE14010402000D","powerSource":0}' from endpoint 1 with groupID 0
  zigbee2mqtt:error 9/18/2019, 11:18:31 AM Failed to call 'DeviceReceive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined
    at mappedDevice.fromZigbee.filter (/opt/zigbee2mqtt/lib/extension/deviceReceive.js:85:42)
    at Array.filter (<anonymous>)
    at DeviceReceive.onZigbeeEvent (/opt/zigbee2mqtt/lib/extension/deviceReceive.js:84:52)
    at Controller.callExtensionMethod (/opt/zigbee2mqtt/lib/controller.js:310:44)
    at Controller.onZigbeeEvent (/opt/zigbee2mqtt/lib/controller.js:221:14)
    at process._tickCallback (internal/process/next_tick.js:68:7))
  serialport/stream _read reading +19ms
  serialport/binding-abstract read +21ms
  serialport/bindings/unixRead Starting read +21ms
  serialport/bindings/unixRead Finished read 8 bytes +1ms
  serialport/stream binding.read finished +3ms
  zigbee-herdsman:unpi:parser <-- [254,3,69,182,0,0,0,240] +14ms
  zigbee-herdsman:unpi:parser --- parseNext [254,3,69,182,0,0,0,240] +1ms
  zigbee-herdsman:unpi:parser --> parsed 3 - 2 - 5 - 182 - [] - 240 +0ms
  zigbee-herdsman:znp:AREQ <-- ZDO - mgmtPermitJoinRsp - {"srcaddr":0,"status":0} +21ms
  zigbee-herdsman:unpi:parser --- parseNext [] +2ms
  serialport/stream _read reading +5ms
  serialport/binding-abstract read +8ms
  serialport/bindings/unixRead Starting read +7ms
  serialport/bindings/unixRead waiting for readable because of code: EAGAIN +1ms
  serialport/bindings/poller Polling for "readable" +32ms
```

**Comment by tb-killa** [comment]
Hi @Koenkk 

it seems that the data doesnt transport correctly :(

```
zigbee-herdsman:controller:log Permit joining +2m
  zigbee-herdsman:znp:SREQ --> ZDO - mgmtPermitJoinReq - {"addrmode":15,"dstaddr":65532,"duration":254,"tcsignificance":0} +2m
  zigbee-herdsman:unpi:writer --> frame [254,5,37,54,15,252,255,254,0,228] +2m
  serialport/stream _write 10 bytes of data +2m
  serialport/binding-abstract write 10 bytes +2m
  serialport/bindings/unixWrite Starting write 10 bytes offset 0 bytesToWrite 10 +2m
  serialport/bindings/unixWrite write returned null 10 +1ms
  serialport/bindings/unixWrite wrote 10 bytes +0ms
  serialport/bindings/unixWrite Finished writing 10 bytes +1ms
  serialport/stream binding.write write finished +6ms
  serialport/bindings/poller received "readable" +2m
  serialport/binding-abstract read +14ms
  serialport/bindings/unixRead Starting read +2m
  serialport/bindings/unixRead Finished read 70 bytes +1ms
  serialport/stream binding.read finished +11ms
  zigbee-herdsman:unpi:parser <-- [254,59,68,129,0,0,0,0,96,52,1,1,0,36,0,164,11,212,0,0,39,24,2,1,4,0,0,66,5,75,111,110,107,101,5,0,0,66,16,51,65,70,69,49,52,48,49,48,52,48,50,48,48,48,68,7,0,0,48,0,96,52,29,224,254,1,101,54,0,82] +2m
  zigbee-herdsman:unpi:parser --- parseNext [254,59,68,129,0,0,0,0,96,52,1,1,0,36,0,164,11,212,0,0,39,24,2,1,4,0,0,66,5,75,111,110,107,101,5,0,0,66,16,51,65,70,69,49,52,48,49,48,52,48,50,48,48,48,68,7,0,0,48,0,96,52,29,224,254,1,101,54,0,82] +1ms
  zigbee-herdsman:unpi:parser --> parsed 59 - 2 - 4 - 129 - [`4$�
                                                                 �'BKonkeB3AFE14010402000D0`4] - 224 +1ms
  zigbee-herdsman:znp:AREQ <-- AF - incomingMsg - {"groupid":0,"clusterid":0,"srcaddr":13408,"srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"linkquality":36,"securityuse":0,"timestamp":13896612,"transseqnumber":0,"len":39,"data":{"type":"Buffer","data":[24,2,1,4,0,0,66,5,75,111,110,107,101,5,0,0,66,16,51,65,70,69,49,52,48,49,48,52,48,50,48,48,48,68,7,0,0,48,0]}} +2m
  zigbee-herdsman:controller:log Received ZCL data '{"frame":{"Header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":true},"transactionSequenceNumber":2,"manufacturerCode":null,"commandIdentifier":1},"Payload":[{"attrId":4,"status":0,"dataType":66,"attrData":"Konke"},{"attrId":5,"status":0,"dataType":66,"attrData":"3AFE14010402000D"},{"attrId":7,"status":0,"dataType":48,"attrData":0}],"ClusterID":0},"networkAddress":13408,"endpoint":1,"linkquality":36,"groupID":0}' +29ms
  zigbee-herdsman:unpi:parser --- parseNext [254,1,101,54,0,82] +6ms
  zigbee-herdsman:unpi:parser --> parsed 1 - 3 - 5 - 54 - [] - 82 +1ms
  zigbee-herdsman:znp:SRSP <-- ZDO - mgmtPermitJoinReq - {"status":0} +2m
  zigbee-herdsman:unpi:parser --- parseNext [] +1ms
  zigbee2mqtt:debug 9/18/2019, 11:48:59 AM Received Zigbee message from '0x086bd7fffee97be7' of type 'readResponse' with data '{"manufacturerName":"Konke","modelId":"3AFE14010402000D","powerSource":0}' from endpoint 1 with groupID 0
  zigbee2mqtt:error 9/18/2019, 11:48:59 AM Failed to call 'DeviceReceive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined
    at mappedDevice.fromZigbee.filter (/opt/zigbee2mqtt/lib/extension/deviceReceive.js:85:42)
    at Array.filter (<anonymous>)
    at DeviceReceive.onZigbeeEvent (/opt/zigbee2mqtt/lib/extension/deviceReceive.js:84:52)
    at Controller.callExtensionMethod (/opt/zigbee2mqtt/lib/controller.js:310:44)
    at Controller.onZigbeeEvent (/opt/zigbee2mqtt/lib/controller.js:221:14)
    at process._tickCallback (internal/process/next_tick.js:68:7))
  serialport/stream _read reading +22ms
  serialport/binding-abstract read +25ms
  serialport/bindings/unixRead Starting read +25ms
  serialport/bindings/unixRead Finished read 8 bytes +1ms
  serialport/stream binding.read finished +3ms
  zigbee-herdsman:unpi:parser <-- [254,3,69,182,0,0,0,240] +15ms
  zigbee-herdsman:unpi:parser --- parseNext [254,3,69,182,0,0,0,240] +1ms
  zigbee-herdsman:unpi:parser --> parsed 3 - 2 - 5 - 182 - [] - 240 +1ms
  zigbee-herdsman:znp:AREQ <-- ZDO - mgmtPermitJoinRsp - {"srcaddr":0,"status":0} +25ms
  zigbee-herdsman:unpi:parser --- parseNext [] +1ms
  serialport/stream _read reading +5ms
  serialport/binding-abstract read +9ms
  serialport/bindings/unixRead Starting read +6ms
  serialport/bindings/unixRead waiting for readable because of code: EAGAIN +1ms
  serialport/bindings/poller Polling for "readable" +36ms
```

This are my database.db entrys, sadly new ones added even after restarting the z2m instance.

```
{"id":14,"type":"EndDevice","ieeeAddr":"0x086bd7fffee97be7","nwkAddr":13408,"manufId":4098,"manufName":"Konke","powerSource":"Unknown","modelId":"3AFE14010402000D","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,1280],"outClusterList":[3],"clusters":{}}},"interviewCompleted":false,"meta":{},"_id":"vYoav5rL14yvaeYD"}
{"id":14,"type":"EndDevice","ieeeAddr":"0x086bd7fffee97be7","nwkAddr":13408,"manufId":4098,"manufName":"Konke","powerSource":"Unknown","modelId":"3AFE14010402000D","epList":[1],"endpoints":{"1":{"epId":1,"inClusterList":[],"outClusterList":[],"clusters":{}}},"interviewCompleted":false,"meta":{},"_id":"vYoav5rL14yvaeYD"}
{"id":14,"type":"EndDevice","ieeeAddr":"0x086bd7fffee97be7","nwkAddr":13408,"manufId":4098,"manufName":"Konke","powerSource":"Unknown","modelId":"3AFE14010402000D","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,1280],"outClusterList":[3],"clusters":{}}},"interviewCompleted":false,"meta":{},"_id":"vYoav5rL14yvaeYD"}
{"id":14,"type":"EndDevice","ieeeAddr":"0x086bd7fffee97be7","nwkAddr":13408,"manufId":4098,"manufName":"Konke","powerSource":"Unknown","modelId":"3AFE14010402000D","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,1280],"outClusterList":[3],"clusters":{}}},"interviewCompleted":false,"meta":{},"_id":"vYoav5rL14yvaeYD"}
```
