### ISSUE TITLE
Interview failed - Xbee S2C Router - CC2530 coordinator

### ISSUE THREAD

**Issue by osmanates** [Koenkk/zigbee-herdsman#372]
I'm getting interview failed error as below while I try to pair an Xbee S2C module.

```
2021-05-23T11:00:24.152Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,178,5,178,5,35]
2021-05-23T11:00:24.602Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2021-05-23T11:00:24.602Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2021-05-23T11:00:24.602Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2021-05-23T11:00:24.603Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2021-05-23T11:00:24.603Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-05-23T11:00:24.623Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,69,196,178]
2021-05-23T11:00:24.623Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,69,196,178]
2021-05-23T11:00:24.624Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [5,0,53]
2021-05-23T11:00:24.624Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,69,196,178,5,0,53]
2021-05-23T11:00:24.624Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 5 - 196 - [178,5,0] - 53
2021-05-23T11:00:24.624Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - srcRtgInd - {"dstaddr":1458,"relaycount":0,"relaylist":[]}
2021-05-23T11:00:24.625Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-05-23T11:00:24.650Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254]
2021-05-23T11:00:24.650Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254]
2021-05-23T11:00:24.651Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [13,69,193,178,5,178,5,76,54,245,64,0,162,19,0,142,121]
2021-05-23T11:00:24.651Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,13,69,193,178,5,178,5,76,54,245,64,0,162,19,0,142,121]
2021-05-23T11:00:24.652Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 13 - 2 - 5 - 193 - [178,5,178,5,76,54,245,64,0,162,19,0,142] - 121
2021-05-23T11:00:24.653Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - endDeviceAnnceInd - {"srcaddr":1458,"nwkaddr":1458,"ieeeaddr":"0x0013a20040f5364c","capabilities":142}
2021-05-23T11:00:24.653Z zigbee-herdsman:controller:log Device announce '0x0013a20040f5364c'
2021-05-23T11:00:24.656Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-05-23T11:00:24.673Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254]
2021-05-23T11:00:24.673Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254]
2021-05-23T11:00:24.674Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [18,69,130,178,5,0,178,5,1,64,142,30,16,82,255,0,0,0,255,0]
2021-05-23T11:00:24.674Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,18,69,130,178,5,0,178,5,1,64,142,30,16,82,255,0,0,0,255,0]
2021-05-23T11:00:24.675Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [0,70]
2021-05-23T11:00:24.675Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,18,69,130,178,5,0,178,5,1,64,142,30,16,82,255,0,0,0,255,0,0,70]
2021-05-23T11:00:24.676Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 18 - 2 - 5 - 130 - [178,5,0,178,5,1,64,142,30,16,82,255,0,0,0,255,0,0] - 70
2021-05-23T11:00:24.676Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - nodeDescRsp - {"srcaddr":1458,"status":0,"nwkaddr":1458,"logicaltype_cmplxdescavai_userdescavai":1,"apsflags_freqband":64,"maccapflags":142,"manufacturercode":4126,"maxbuffersize":82,"maxintransfersize":255,"servermask":0,"maxouttransfersize":255,"descriptorcap":0}
2021-05-23T11:00:24.677Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-05-23T11:00:24.680Z zigbee-herdsman:controller:device:log Interview - got node descriptor for device '0x0013a20040f5364c'
2021-05-23T11:00:24.682Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - activeEpReq - {"dstaddr":1458,"nwkaddrofinterest":1458}
2021-05-23T11:00:24.682Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,5,178,5,178,5,36]
2021-05-23T11:00:24.696Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254]
2021-05-23T11:00:24.697Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254]
2021-05-23T11:00:24.698Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [1,101,5,0,97]
2021-05-23T11:00:24.698Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,5,0,97]
2021-05-23T11:00:24.698Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 5 - [0] - 97
2021-05-23T11:00:24.699Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - activeEpReq - {"status":0}
2021-05-23T11:00:24.699Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-05-23T11:00:34.701Z zigbee-herdsman:controller:device:log Interview - active endpoints request failed for '0x0013a20040f5364c', attempt 1
2021-05-23T11:00:34.702Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - activeEpReq - {"dstaddr":1458,"nwkaddrofinterest":1458}
2021-05-23T11:00:34.702Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,5,178,5,178,5,36]
2021-05-23T11:00:34.715Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254]
2021-05-23T11:00:34.715Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254]
2021-05-23T11:00:34.715Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [1,101]
2021-05-23T11:00:34.715Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101]
2021-05-23T11:00:34.716Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [5,0,97]
2021-05-23T11:00:34.716Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,5,0,97]
2021-05-23T11:00:34.716Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 5 - [0] - 97
2021-05-23T11:00:34.716Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - activeEpReq - {"status":0}
2021-05-23T11:00:34.717Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-05-23T11:00:34.951Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254]
2021-05-23T11:00:34.951Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254]
2021-05-23T11:00:34.952Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [3,69,196,178,5,0,53]
2021-05-23T11:00:34.952Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,69,196,178,5,0,53]
2021-05-23T11:00:34.952Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 5 - 196 - [178,5,0] - 53
2021-05-23T11:00:34.953Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - srcRtgInd - {"dstaddr":1458,"relaycount":0,"relaylist":[]}
2021-05-23T11:00:34.953Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-05-23T11:00:35.005Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254]
2021-05-23T11:00:35.006Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254]
2021-05-23T11:00:35.006Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [7,69,133,178,5,0,178,5,1,5,195]
2021-05-23T11:00:35.007Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,7,69,133,178,5,0,178,5,1,5,195]
2021-05-23T11:00:35.007Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 7 - 2 - 5 - 133 - [178,5,0,178,5,1,5] - 195
2021-05-23T11:00:35.007Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - activeEpRsp - {"srcaddr":1458,"status":0,"nwkaddr":1458,"activeepcount":1,"activeeplist":[5]}
2021-05-23T11:00:35.008Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-05-23T11:00:35.010Z zigbee-herdsman:controller:device:log Interview - got active endpoints for device '0x0013a20040f5364c'
2021-05-23T11:00:35.012Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - simpleDescReq - {"dstaddr":1458,"nwkaddrofinterest":1458,"endpoint":5}
2021-05-23T11:00:35.012Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,5,37,4,178,5,178,5,5,33]
2021-05-23T11:00:35.025Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254]
2021-05-23T11:00:35.025Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254]
2021-05-23T11:00:35.026Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [1,101,4,0,96]
2021-05-23T11:00:35.038Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,4,0,96]
2021-05-23T11:00:35.039Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 4 - [0] - 96
2021-05-23T11:00:35.039Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - simpleDescReq - {"status":0}
2021-05-23T11:00:35.039Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-05-23T11:00:35.309Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,69,196,178,5,0,53]
2021-05-23T11:00:35.310Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,69,196,178,5,0,53]
2021-05-23T11:00:35.310Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 5 - 196 - [178,5,0] - 53
2021-05-23T11:00:35.310Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - srcRtgInd - {"dstaddr":1458,"relaycount":0,"relaylist":[]}
2021-05-23T11:00:35.311Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-05-23T11:00:35.362Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254]
2021-05-23T11:00:35.362Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254]
2021-05-23T11:00:35.363Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [20,69,132,178,5,0,0,0,14,5,4,1]
2021-05-23T11:00:35.363Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,20,69,132,178,5,0,0,0,14,5,4,1]
2021-05-23T11:00:35.364Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [2,0,48,3,0,0,3,0,6,0]
2021-05-23T11:00:35.364Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,20,69,132,178,5,0,0,0,14,5,4,1,2,0,48,3,0,0,3,0,6,0]
2021-05-23T11:00:35.365Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [0,88]
2021-05-23T11:00:35.365Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,20,69,132,178,5,0,0,0,14,5,4,1,2,0,48,3,0,0,3,0,6,0,0,88]
2021-05-23T11:00:35.365Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 20 - 2 - 5 - 132 - [178,5,0,0,0,14,5,4,1,2,0,48,3,0,0,3,0,6,0,0] - 88
2021-05-23T11:00:35.366Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - simpleDescRsp - {"srcaddr":1458,"status":0,"nwkaddr":0,"len":14,"endpoint":5,"profileid":260,"deviceid":2,"deviceversion":48,"numinclusters":3,"inclusterlist":[0,3,6],"numoutclusters":0,"outclusterlist":[]}
2021-05-23T11:00:35.366Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-05-23T11:00:45.041Z zigbee-herdsman:controller:device:log Interview - failed for device '0x0013a20040f5364c' with error 'Error: AREQ - ZDO - simpleDescRsp after 10000ms
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:37:35)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)'
2021-05-23T11:00:45.043Z zigbee-herdsman:controller:error Interview failed for '0x0013a20040f5364c with error 'Error: AREQ - ZDO - simpleDescRsp after 10000ms'
Zigbee2MQTT:error 2021-05-23 14:00:45: Failed to interview '0x0013a20040f5364c', device has not successfully been paired
```

I'm using XBEE with an Arduino nano to send/receive ZCL messages so that in the end I'm planning to create my own router/end devices using Atmega328P directly. I got XBEE to join the network successfully. It sends Device Announcement requests and in response Z2M sends Node Descriptor request. But after Xbee sends SimpleDescriptor response successfully, I get error as in the log. I also attached sniffer screenshot.

![ss4](https://user-images.githubusercontent.com/982467/119258198-5e532b80-bbd1-11eb-80b8-7eab28fad7fa.png)

**Comment by osmanates** [comment]
I found the issue. It was my mistake when creating payload for the SimpleDescriptorResponse. I'm closing this but it would be nice if there was a some kind of guide that explains what requests Zigbee2Mqtt creates and what kind of responses it expects. Thanks
