### ISSUE TITLE
Errors with latest Zigbee2MQTT

### ISSUE THREAD

**Issue by Kryzek** [Koenkk/zigbee-herdsman#57]
I updated to latest development version of Zigbee2MQTT and I'm getting this kind of errors all the time now.
Seems to be something within Zigbee-Herdsman. 
```
zigbee2mqtt:error 2019-10-07T07:44:06: Publish 'set' 'state' to '0x00158d0001d0f272' failed: 'Error: SRSP - AF - dataRequest after 6000ms'
zigbee2mqtt:info  2019-10-07T07:44:06: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'state' to '0x00158d0001d0f272' failed: 'Error: SRSP - AF - dataRequest after 6000ms'","meta":{"friendly_name":"0x00158d0001d0f272"}}'
(node:25609) UnhandledPromiseRejectionWarning: Error: AREQ - AF - dataConfirm after 10000ms
    at Timeout.object.timer.setTimeout [as _onTimeout] (/opt/zigbee2mqtt-herdsman/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:25609) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
(node:25609) UnhandledPromiseRejectionWarning: Error: AREQ - AF - dataConfirm after 10000ms
    at Timeout.object.timer.setTimeout [as _onTimeout] (/opt/zigbee2mqtt-herdsman/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:25609) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
(node:25609) UnhandledPromiseRejectionWarning: Error: AREQ - AF - dataConfirm after 10000ms
    at Timeout.object.timer.setTimeout [as _onTimeout] (/opt/zigbee2mqtt-herdsman/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:25609) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
(node:25609) UnhandledPromiseRejectionWarning: Error: AREQ - AF - dataConfirm after 10000ms
    at Timeout.object.timer.setTimeout [as _onTimeout] (/opt/zigbee2mqtt-herdsman/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
zigbee2mqtt:error 2019-10-07T07:46:10: Publish 'set' 'state' to '0x000b57fffe8be58f' failed: 'Error: SRSP - AF - dataRequest after 6000ms'
zigbee2mqtt:info  2019-10-07T07:46:10: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'state' to '0x000b57fffe8be58f' failed: 'Error: SRSP - AF - dataRequest after 6000ms'","meta":{"friendly_name":"0x000b57fffe8be58f"}}'
(node:25609) UnhandledPromiseRejectionWarning: Error: AREQ - AF - dataConfirm after 10000ms
    at Timeout.object.timer.setTimeout [as _onTimeout] (/opt/zigbee2mqtt-herdsman/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:25609) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
zigbee2mqtt:error 2019-10-07T07:46:37: Publish 'set' 'state' to '0x00124b001d3ab1b9' failed: 'Error: SRSP - AF - dataRequest after 6000ms'
zigbee2mqtt:info  2019-10-07T07:46:37: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'state' to '0x00124b001d3ab1b9' failed: 'Error: SRSP - AF - dataRequest after 6000ms'","meta":{"friendly_name":"0x00124b001d3ab1b9"}}'
(node:25609) UnhandledPromiseRejectionWarning: Error: AREQ - AF - dataConfirm after 10000ms
    at Timeout.object.timer.setTimeout [as _onTimeout] (/opt/zigbee2mqtt-herdsman/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:25609) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)



```

**Comment by Kryzek** [comment]
Any of the paired devices is not responding or reacting to any command.

**Comment by Kryzek** [comment]
And it seems I cannot get running Zigbee2mqtt with current or older version (tried rebooting my raspberry pi and problem persists).

Older revision:
```
  zigbee2mqtt:info 10/7/2019, 1:36:27 PM Logging to directory: '/opt/zigbee2mqtt-backup/data/log/2019-10-07.13-36-26'
  zigbee2mqtt:info 10/7/2019, 1:36:27 PM Starting zigbee2mqtt version 1.6.0 (commit #9d4705f)
  zigbee2mqtt:info 10/7/2019, 1:36:27 PM Starting zigbee-herdsman...
  zigbee2mqtt:error 10/7/2019, 1:36:39 PM Error while starting zigbee-herdsman
  zigbee2mqtt:error 10/7/2019, 1:36:39 PM Error: SRSP - SYS - version after 6000ms
    at Timeout.object.timer.setTimeout [as _onTimeout] (/opt/zigbee2mqtt-backup/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  zigbee2mqtt:error 10/7/2019, 1:36:39 PM Failed to start zigbee
  zigbee2mqtt:error 10/7/2019, 1:36:39 PM Exiting...
  zigbee2mqtt:error 10/7/2019, 1:36:39 PM Error: SRSP - SYS - version after 6000ms
    at Timeout.object.timer.setTimeout [as _onTimeout] (/opt/zigbee2mqtt-backup/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

and current version gives also same error:
```
zigbee2mqtt:info  2019-10-07T10:39:34: Logging to directory: '/opt/zigbee2mqtt-herdsman/data/log/2019-10-07.13-39-32'
zigbee2mqtt:info  2019-10-07T10:39:34: Starting zigbee2mqtt version 1.6.0 (commit #41c8c2a)
zigbee2mqtt:info  2019-10-07T10:39:34: Starting zigbee-herdsman...
zigbee2mqtt:error 2019-10-07T10:39:46: Error while starting zigbee-herdsman
zigbee2mqtt:error 2019-10-07T10:39:46: Error: SRSP - SYS - version after 6000ms
    at Timeout.object.timer.setTimeout [as _onTimeout] (/opt/zigbee2mqtt-herdsman/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
zigbee2mqtt:error 2019-10-07T10:39:46: Failed to start zigbee
zigbee2mqtt:error 2019-10-07T10:39:46: Exiting...
zigbee2mqtt:error 2019-10-07T10:39:46: Error: SRSP - SYS - version after 6000ms
    at Timeout.object.timer.setTimeout [as _onTimeout] (/opt/zigbee2mqtt-herdsman/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

**Comment by Kryzek** [comment]
It seems my stick got flipped since I have these on my system log:
```
cdc_acm 1-1.3:1.0: failed to set dtr/rts
```

Need to check wheter it will be ok after I get to remove and re-insert usb-sniffer. (Not near device atm).

**Comment by Kryzek** [comment]
I got Z2M started with older version but it dies immediately after starting.

[z2m-err.txt](https://github.com/Koenkk/zigbee-herdsman/files/3696968/z2m-err.txt)

Could these repeated messages could be the reason?
```
10/7/2019, 2:30:53 PM - info: MQTT publish: topic 'zigbee2mqtt/0x00158d0001cded1c', payload '{"state":"OFF","linkquality":39,"brightness":242}'
```

This device (0x00158d0001cded1c): 4713407 - Airam LED OP A60 ZB 9W/827 E27 (Router) is spamming network so much that network just chokes?

**Comment by Kryzek** [comment]
My Airam bulbs went crazy after update and this caused this problem.
