### ISSUE TITLE
syntax error in table.ts

### ISSUE THREAD

**Issue by bruno4712** [Koenkk/zigbee-herdsman#729]
I get following dump running ioBroker:

Error: Table length not divisible by entry length (alignment=aligned, data_length=253, entry_length=12. Therefore structure mapped can not used in iobroker.zigbee.

<html>
<body>

2023-07-05 15:23:01.414 - error: zigbee.0 (13262) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
--
2023-07-05 15:23:01.416 - error: zigbee.0 (13262) unhandled promise rejection: Cannot read properties of undefined (reading 'mapped')
2023-07-05 15:23:01.419 - error: zigbee.0 (13262) TypeError: Cannot read properties of undefined (reading 'mapped')
at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:571:36)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-07-05 15:23:01.420 - error: zigbee.0 (13262) Cannot read properties of undefined (reading 'mapped')
2023-07-05 15:23:01.434 - info: zigbee.0 (13262) cleaned everything up...
2023-07-05 15:23:01.472 - info: zigbee.0 (13262) Zigbee: disabling joining new devices.
2023-07-05 15:23:02.130 - error: zigbee.0 (13262) Failed to stop zigbee (Error: Table length not divisible by entry length (alignment=aligned, data_length=253, entry_length=12)
at Table.build (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/structs/table.ts:181:23)
at addressManagerTable (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/structs/entries/address-manager-table.ts:20:19)
at AdapterNvMemory.readItem (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/adapter-nv-memory.ts:73:21)
at AdapterBackup.createBackup (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/adapter-backup.ts:98:37)
at Controller.backup (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/controller.ts:328:28)
at Controller.stop (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/controller.ts:308:9)
at ZigbeeController.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:455:13)
at Zigbee.onUnload (/opt/iobroker/node_modules/iobroker.zigbee/main.js:853:17))
2023-07-05 15:23:02.133 - info: zigbee.0 (13262) terminating
2023-07-05 15:23:02.136 - warn: zigbee.0 (13262) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-07-05 15:23:02.735 - error: host.iobrokertc Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-07-05 15:23:02.736 - error: host.iobrokertc Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'mapped')
2023-07-05 15:23:02.737 - error: host.iobrokertc Caught by controller[1]: at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:571:36)
2023-07-05 15:23:02.737 - error: host.iobrokertc Caught by controller[1]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-07-05 15:23:02.737 - error: host.iobrokertc instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

</body>
</html>

**Comment by bruno4712** [comment]
Upgrade to Zigbee v1.8.16 will help to fix this now. I hope so. No dump occurs now.
